## View(Reshape)

In [1]:
import numpy as np
import torch
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
             
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [2]:
print(ft.view([-1, 3]))  # (2 x 2, 3) = (4, 3)
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [3]:
print(ft.view([-1, 1, 3]))  # (2 x 2, 1, 3) = (4, 1, 3)
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


## Squeeze

- 차원의 element 개수가 1인 경우, 그 차원을 제거

In [4]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [5]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [6]:
print(ft.squeeze(dim=1))  # 해당 dimension에 1이 있을 경우 제거
print(ft.squeeze(dim=0))  # 변화 x

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])


## Unsqueeze


- 특정 위치에 1인 차원을 추가

In [7]:
ft = torch.FloatTensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [8]:
print(ft.unsqueeze(0))  # dim=0에 1인 차원 추가
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [9]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [10]:
print(ft.unsqueeze(1))  # dim=1
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [11]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


## Type Casting
- Tensor의 Type을 변환
- ByteTensor : 어떤 조건문을 만족하는 연산을 수행했을 때 자동으로 ByteTensor가 생성됨

In [12]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [13]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [14]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [15]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


## Concatenate

In [16]:
x = torch.FloatTensor([[1, 2], [3, 4]])  # |x| = |y| = (2, 2)
y = torch.FloatTensor([[5, 6], [7, 8]])

In [17]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [18]:
x = torch.FloatTensor([1, 2])
y = torch.FloatTensor([5, 6])
print(torch.stack([x, y], dim=1))
                           

tensor([[1., 5.],
        [2., 6.]])


## Stacking
- concatenate를 좀 더 편리하게

In [19]:
x = torch.FloatTensor([1, 4])  # |x| = |y| = |z| = (2,)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [20]:
print(torch.stack([x, y, z]))         # (3, 2)
print(torch.stack([x, y, z], dim=1))  # (2, 3) -> 새로 생기는 차원이 dim=1이 됨

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [21]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


## Ones and Zeros

In [22]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)  # |x| = (2, 3)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [23]:
print(torch.ones_like(x))  # 같은 device에 Tensor를 선언해 줌
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## In-place Operation

In [24]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [25]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))  # 메모리에 새로 선언하지 않고, 계산된 값을 기존의 Tensor에 넣음
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])
