# Lab 1: PyTorch Basic Tensor Manipulation
> - Vector, Matrix and Tensor
> - NumPy Review
> - PyTorch Tensor Allocation
> - Matrix Multiplication
> - Other Basic Ops

#### PyTorch Tensor Shape Convention



- 2D Tensor (Typical Simple Setting)
    - |t| = (batch size, dim)
    
    
- 3D Tensor (Typical Computer Vision)
    - 여러 장의 이미지(vision)  
    - |t| = (batch size, width, height)
    
    
- 3D Tensor (Typical Natural Language Processing)
    - 시계열 data, sequential data  
    - |t| = (batch size, length, dim)
    

## Import

In [1]:
import numpy as np
import torch

## NumPy Review

### 1D Array with NumPy

In [2]:
t = np.array([0., 1., 2., 3., 4., 5., 6.])  
print(t)

[0. 1. 2. 3. 4. 5. 6.]


In [3]:
print('Rank of t: ', t.ndim)    # 1차원의 vector
print('Shape of t: ', t.shape)  # 하나의 차원은 7개의 element로 구성

Rank of t:  1
Shape of t:  (7,)


In [4]:
print('t[0] t[1] t[-1] = ', t[0], t[1], t[-1])  # Element
print('t[2:5] t[4:-1]  = ', t[2:5], t[4:-1])    # Slicing
print('t[:2] t[3:]     = ', t[:2], t[3:])       # Slicing

t[0] t[1] t[-1] =  0.0 1.0 6.0
t[2:5] t[4:-1]  =  [2. 3. 4.] [4. 5.]
t[:2] t[3:]     =  [0. 1.] [3. 4. 5. 6.]


### 2D Array with NumPy

In [5]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])
print(t)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]


In [6]:
print('Rank of t: ', t.ndim)
print('Shape of t: ', t.shape)

Rank of t:  2
Shape of t:  (4, 3)


## PyTorch Tensor

### 1D Array with PyTorch

In [7]:
t = torch.FloatTensor([0., 1., 2., 3., 4., 5., 6.])
print(t[0], t[1])

tensor(0.) tensor(1.)


In [8]:
print(t.dim())            # rank
print(t.shape)            # shape
print(t.size())           # shape
print(t[0], t[1], t[-1])  # Element
print(t[2:5], t[4:-1])    # Slicing
print(t[:2], t[3:])       # Slicing

1
torch.Size([7])
torch.Size([7])
tensor(0.) tensor(1.) tensor(6.)
tensor([2., 3., 4.]) tensor([4., 5.])
tensor([0., 1.]) tensor([3., 4., 5., 6.])


### 2D Array with PyTorch

In [9]:
t = torch.FloatTensor([[1., 2., 3.],
                       [4., 5., 6.],
                       [7., 8., 9.],
                       [10., 11., 12.]
                      ])
print(t)

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.]])


In [10]:
print(t.dim())            # rank
print(t.size())           # shape
print(t[:, 1])                        
print(t[:, 1].size())
print(t[:, :-1])   

2
torch.Size([4, 3])
tensor([ 2.,  5.,  8., 11.])
torch.Size([4])
tensor([[ 1.,  2.],
        [ 4.,  5.],
        [ 7.,  8.],
        [10., 11.]])


In [11]:
t = torch.FloatTensor([[[[1, 2, 3, 4],
                        [5, 6, 7, 8],
                        [9, 10, 11, 12]],
                        [[13, 14, 15, 16],
                        [17, 18, 19, 20],
                        [21, 22, 23, 24]]
                        ]])

In [12]:
print(t.dim())   # rank = 4  
print(t.size())  # shape = (1, 2, 3, 4)

4
torch.Size([1, 2, 3, 4])


## Frequently Used Operations in PyTorch

### Broadcasting

- 모양이 다른 tensor들 간의 연산이 가능해지도록 tensor의 사이즈를 자동으로 변환

In [13]:
# Same shape
m1 = torch.FloatTensor([[3, 3]])
m2 = torch.FloatTensor([[2, 2]])
print(m1 + m2)

tensor([[5., 5.]])


In [14]:
# Vector + scalar
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([3])  # 3 -> [[3, 3]]
print(m1 + m2)

tensor([[4., 5.]])


In [15]:
# 1 x 2 Vector + 2 x 1 Vector
m1 = torch.FloatTensor([[1, 2]])
m2 = torch.FloatTensor([[3], [4]])
print(m1 + m2)  # |m1|, |m2| =(2, 2)

tensor([[4., 5.],
        [5., 6.]])


### Multiplication vs Matrix Multiplication

In [16]:
print()
print('-------------')
print('Mul vs Matmul')
print('-------------')
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)  # 2 x 2
print('Shape of Matrix 2: ', m2.shape)  # 2 x 1
print(m1.matmul(m2))                    # 2 x 1, dot(=inner) produt(행렬 곱셈)
 
m1 = torch.FloatTensor([[1, 2], [3, 4]])
m2 = torch.FloatTensor([[1], [2]])
print('Shape of Matrix 1: ', m1.shape)  # 2 x 2
print('Shape of Matrix 2: ', m2.shape)  # 2 x 1
print(m1 * m2)                          # 2 x 2, element-wise(일반적인 곱셈)
print(m1.mul(m2))                       


-------------
Mul vs Matmul
-------------
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[ 5.],
        [11.]])
Shape of Matrix 1:  torch.Size([2, 2])
Shape of Matrix 2:  torch.Size([2, 1])
tensor([[1., 2.],
        [6., 8.]])
tensor([[1., 2.],
        [6., 8.]])


### Mean

In [17]:
t = torch.FloatTensor([1, 2])
print(t.mean())

tensor(1.5000)


In [18]:
# Can't use mean() on integers
t = torch.LongTensor([1, 2])
try:
    print(t.mean())
except Exception as exc:
    print(exc)

Can only calculate the mean of floating types. Got Long instead.


In [19]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t, t.size())

tensor([[1., 2.],
        [3., 4.]]) torch.Size([2, 2])


In [20]:
print(t.mean())
print(t.mean(dim=0))  # 2 x 2 -> 1 x 2 (2,)
print(t.mean(dim=1))  # 2 x 2 -> 2 x 1 (2,)
print(t.mean(dim=-1))

tensor(2.5000)
tensor([2., 3.])
tensor([1.5000, 3.5000])
tensor([1.5000, 3.5000])


In [21]:
# 차원 참고
e = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(e, e.size())
print(e.mean(dim=0))
print(e.mean(dim=0).size())
print(e.mean(dim=1).size())

c = torch.FloatTensor([[1], [2]]).size()
print(c)

tensor([[1., 2., 3.],
        [4., 5., 6.]]) torch.Size([2, 3])
tensor([2.5000, 3.5000, 4.5000])
torch.Size([3])
torch.Size([2])
torch.Size([2, 1])


### Sum

In [22]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


In [23]:
print(t.sum())
print(t.sum(dim=0))
print(t.sum(dim=1).shape)
print(t.sum(dim=-1))

tensor(10.)
tensor([4., 6.])
torch.Size([2])
tensor([3., 7.])


### Max and Argmax

In [24]:
t = torch.FloatTensor([[1, 2], [3, 4]])
print(t)

tensor([[1., 2.],
        [3., 4.]])


The max operator returns one value if it is called without an argument.

In [25]:
print(t.max())  # Returns one value: max

tensor(4.)


The max operator returns 2 values when called with dimension specified.

In [26]:
print(t.max(dim=0))  # Returns two values: max and argmax(인덱스 값)
print('Max: ', t.max(dim=0)[0])
print('ArgMax: ', t.max(dim=0)[1])

torch.return_types.max(
values=tensor([3., 4.]),
indices=tensor([1, 1]))
Max:  tensor([3., 4.])
ArgMax:  tensor([1, 1])


In [27]:
print(t.max(dim=1))
print(t.max(dim=-1))

torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))
torch.return_types.max(
values=tensor([2., 4.]),
indices=tensor([1, 1]))


### View (Reshape)

In [28]:
import numpy as np
import torch
t = np.array([[[0, 1, 2],
               [3, 4, 5]],
             
              [[6, 7, 8],
               [9, 10, 11]]])
ft = torch.FloatTensor(t)
print(ft.shape)

torch.Size([2, 2, 3])


In [29]:
print(ft.view([-1, 3]))  # (2 x 2, 3) = (4, 3)
print(ft.view([-1, 3]).shape)

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


In [30]:
print(ft.view([-1, 1, 3]))  # (2 x 2, 1, 3) = (4, 1, 3)
print(ft.view([-1, 1, 3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])


### Squeeze
- 차원의 element 개수가 1인 경우, 그 차원을 제거

In [31]:
ft = torch.FloatTensor([[0], [1], [2]])
print(ft)
print(ft.shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [32]:
print(ft.squeeze())
print(ft.squeeze().shape)

tensor([0., 1., 2.])
torch.Size([3])


In [33]:
print(ft.squeeze(dim=1))  # 해당 dimension에 1이 있을 경우 제거
print(ft.squeeze(dim=0))  # 변화 x

tensor([0., 1., 2.])
tensor([[0.],
        [1.],
        [2.]])


### Unsqueeze


- 특정 위치(dimension)에 1인 차원을 추가

In [34]:
ft = torch.FloatTensor([0, 1, 2])
print(ft)
print(ft.shape)

tensor([0., 1., 2.])
torch.Size([3])


In [35]:
print(ft.unsqueeze(0))  # dim=0에 1인 차원 추가
print(ft.unsqueeze(0).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [36]:
print(ft.view(1, -1))
print(ft.view(1, -1).shape)

tensor([[0., 1., 2.]])
torch.Size([1, 3])


In [37]:
print(ft.unsqueeze(1))  # dim=1
print(ft.unsqueeze(1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


In [38]:
print(ft.unsqueeze(-1))
print(ft.unsqueeze(-1).shape)

tensor([[0.],
        [1.],
        [2.]])
torch.Size([3, 1])


### Scatter (for one-hot encoding)
- Scatter is a very flexible function
- We only discuss how to use it to get a one-hot encoding of indices

In [39]:
lt = torch.LongTensor([[0], [1], [2], [0]])  # scatter의 index가 LongTensor type을 받음
print(lt)

tensor([[0],
        [1],
        [2],
        [0]])


In [40]:
one_hot = torch.zeros(4, 3)  # batch_size = 4, classes = 3
one_hot.scatter_(1, lt, 1)   # scatter(dim, index, value) 
print(one_hot)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [1., 0., 0.]])


### Type Casting
- Tensor의 Type을 변환
- ByteTensor : 어떤 조건문을 만족하는 연산을 수행했을 때, 자동으로 ByteTensor가 생성됨

In [41]:
lt = torch.LongTensor([1, 2, 3, 4])
print(lt)

tensor([1, 2, 3, 4])


In [42]:
print(lt.float())

tensor([1., 2., 3., 4.])


In [43]:
bt = torch.ByteTensor([True, False, False, True])
print(bt)

tensor([1, 0, 0, 1], dtype=torch.uint8)


In [44]:
print(bt.long())
print(bt.float())

tensor([1, 0, 0, 1])
tensor([1., 0., 0., 1.])


### Concatenate

In [45]:
x = torch.FloatTensor([[1, 2], [3, 4]])  # |x| = |y| = (2, 2)
y = torch.FloatTensor([[5, 6], [7, 8]])

In [46]:
print(torch.cat([x, y], dim=0))
print(torch.cat([x, y], dim=1))

tensor([[1., 2.],
        [3., 4.],
        [5., 6.],
        [7., 8.]])
tensor([[1., 2., 5., 6.],
        [3., 4., 7., 8.]])


In [47]:
# stack과 비교
x = torch.FloatTensor([1, 2])
y = torch.FloatTensor([5, 6])
print(torch.stack([x, y], dim=1))

tensor([[1., 5.],
        [2., 6.]])


### Stacking
- concatenate를 좀 더 편리하게

In [48]:
x = torch.FloatTensor([1, 4])  # |x| = |y| = |z| = (2,)
y = torch.FloatTensor([2, 5])
z = torch.FloatTensor([3, 6])

In [49]:
print(torch.stack([x, y, z]))         # (3, 2)
print(torch.stack([x, y, z], dim=1))  # (2, 3) -> 새로 생기는 차원이 dim=1이 됨

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])


In [50]:
print(torch.cat([x.unsqueeze(0), y.unsqueeze(0), z.unsqueeze(0)], dim=0))

tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


### Ones and Zeros

In [51]:
x = torch.FloatTensor([[0, 1, 2], [2, 1, 0]])
print(x)  # |x| = (2, 3)

tensor([[0., 1., 2.],
        [2., 1., 0.]])


In [52]:
print(torch.ones_like(x))  # 같은 device에 Tensor를 선언해 줌
print(torch.zeros_like(x))

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


### In-place Operation

In [53]:
x = torch.FloatTensor([[1, 2], [3, 4]])

In [54]:
print(x.mul(2.))
print(x)
print(x.mul_(2.))  # 메모리에 새로 선언하지 않고, 계산된 값을 기존의 Tensor에 넣음
print(x)

tensor([[2., 4.],
        [6., 8.]])
tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 4.],
        [6., 8.]])
tensor([[2., 4.],
        [6., 8.]])


### Miscellaneous

### Zip

In [55]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [56]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9
